In [1]:
import pandas  as pd

In [2]:
iris=pd.read_csv("iris1.csv")

In [3]:
iris

,sepal-length,sepal-width,petal-length,petal-width,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
iris.head()

   sepal-length    sepal-width    petal-length    petal-width        class
0             5.1            3.5             1.4          0.2  Iris-setosa
1             4.9            3.0             1.4          0.2  Iris-setosa
2             4.7            3.2             1.3          0.2  Iris-setosa
3             4.6            3.1             1.5          0.2  Iris-setosa
4             5.0            3.6             1.4          0.2  Iris-setosa

In [17]:
iris['sepal-length']>4

KeyError: 'sepal-length'