In [5]:
x='helllo'
x

'helllo'

In [6]:
import pandas as pd
import numpy as np

In [12]:
path='Auto85.csv'
df = pd.read_csv(path, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [15]:
a = ["symboling","normalized-losses","make","fuel-type", "aspiration", "num-of-doors", "body-style", "drive-wheels","engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "Price"]

In [16]:
df.columns=a
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,Price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [17]:
df["normalized-losses"].replace("?", np.nan, inplace = True)
df["normalized-losses"]=pd.to_numeric(df["normalized-losses"])
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,Price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [18]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
Price                 object
dtype: object

In [19]:
mean=df['normalized-losses'].mean()
mean

122.0

In [20]:
df["normalized-losses"].replace(np.nan,mean,inplace=True)
df["normalized-losses"]

0      122.0
1      122.0
2      122.0
3      164.0
4      164.0
       ...
200     95.0
201     95.0
202     95.0
203     95.0
204     95.0
Name: normalized-losses, Length: 205, dtype: float64

In [21]:
df[["normalized-losses","make"]]

     normalized-losses         make
0                122.0  alfa-romero
1                122.0  alfa-romero
2                122.0  alfa-romero
3                164.0         audi
4                164.0         audi
..                 ...          ...
200               95.0        volvo
201               95.0        volvo
202               95.0        volvo
203               95.0        volvo
204               95.0        volvo

[205 rows x 2 columns]

In [22]:
t=df.groupby("make").mean()
t

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
make,,,,,,,,,,,
alfa-romero,2.333333,122.000000,90.566667,169.600000,64.566667,50.000000,2639.666667,137.333333,9.000000,20.333333,26.666667
audi,1.285714,144.285714,102.271429,183.828571,68.714286,54.428571,2800.714286,130.714286,8.400000,18.857143,24.142857
bmw,0.375000,156.000000,103.162500,184.500000,66.475000,54.825000,2929.375000,166.875000,8.575000,19.375000,25.375000
chevrolet,1.000000,100.000000,92.466667,151.933333,62.500000,52.400000,1757.000000,80.333333,9.566667,41.000000,46.333333
dodge,1.000000,133.444444,95.011111,160.988889,64.166667,51.644444,2151.333333,102.666667,8.634444,28.000000,34.111111
honda,0.615385,103.000000,94.330769,160.769231,64.384615,53.238462,2096.769231,99.307692,9.215385,30.384615,35.461538
isuzu,0.750000,122.000000,94.825000,163.775000,63.550000,52.225000,2213.500000,102.500000,9.225000,31.000000,36.000000
jaguar,0.000000,129.666667,109.333333,196.966667,69.933333,51.133333,4027.333333,280.666667,9.233333,14.333333,18.333333
mazda,1.117647,123.705882,97.017647,170.805882,65.588235,53.358824,2297.823529,103.000000,10.488235,25.705882,31.941176
mercedes-benz,0.000000,110.000000,110.925000,195.262500,71.062500,55.725000,3696.250000,226.500000,14.825000,18.500000,21.000000
mercury,1.000000,122.000000,102.700000,178.400000,68.000000,54.800000,2910.000000,140.000000,8.000000,19.000000,24.000000
mitsubishi,1.846154,140.615385,95.353846,168.030769,65.253846,50.692308,2381.923077,118.307692,8.061538,24.923077,31.153846
nissan,1.000000,135.166667,95.722222,170.988889,65.088889,53.633333,2400.388889,127.888889,9.794444,27.000000,32.944444
peugot,0.000000,146.818182,110.200000,191.136364,68.390909,57.181818,3221.000000,135.818182,14.000000,22.454545,26.636364
plymouth,1.000000,128.000000,95.385714,164.900000,64.271429,51.971429,2220.857143,106.285714,8.671429,28.142857,34.142857
porsche,2.600000,134.800000,92.280000,170.260000,67.120000,51.100000,2891.200000,187.200000,9.600000,17.400000,26.000000
renault,1.000000,122.000000,96.100000,179.150000,66.550000,52.850000,2519.500000,132.000000,8.700000,23.000000,31.000000
saab,2.500000,127.000000,99.100000,186.600000,66.500000,56.100000,2745.500000,121.000000,9.201667,20.333333,27.333333
subaru,0.500000,92.250000,96.175000,168.858333,64.950000,53.750000,2316.250000,107.083333,8.816667,26.333333,30.750000
toyota,0.562500,110.656250,98.103125,171.934375,65.090625,53.721875,2441.093750,118.812500,10.340625,27.500000,32.906250
volkswagen,1.666667,121.500000,97.608333,172.533333,65.616667,55.183333,2343.166667,107.250000,13.625000,28.583333,34.916667
volvo,-1.272727,91.454545,106.481818,188.800000,67.963636,56.236364,3037.909091,142.272727,10.227273,21.181818,25.818182

In [23]:
df['city-mpg']

0      21
1      21
2      19
3      24
4      18
       ..
200    23
201    19
202    18
203    26
204    19
Name: city-mpg, Length: 205, dtype: int64

In [24]:
df['city-mpg']=235/df ['city-mpg']
df['city-mpg']

0      11.190476
1      11.190476
2      12.368421
3       9.791667
4      13.055556
         ...
200    10.217391
201    12.368421
202    13.055556
203     9.038462
204    12.368421
Name: city-mpg, Length: 205, dtype: float64

In [25]:
df.rename(columns={'city-mpg':'c-L/100km'},inplace=True)
df['c-L/100km']

0      11.190476
1      11.190476
2      12.368421
3       9.791667
4      13.055556
         ...
200    10.217391
201    12.368421
202    13.055556
203     9.038462
204    12.368421
Name: c-L/100km, Length: 205, dtype: float64

In [26]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,c-L/100km,highway-mpg,Price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450

In [28]:
df["Price"].dtype

dtype('O')

In [36]:
df["Price"].replace("?",np.nan, inplace=True)
df["Price"]=pd. to_numeric(df["Price"])
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,c-L/100km,highway-mpg,Price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,10.217391,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,12.368421,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,13.055556,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,9.038462,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,12.368421,25,22625.0

In [38]:
df["Price"].dtype

dtype('float64')

In [42]:
df["highway-mpg"]

0      27
1      27
2      26
3      30
4      22
       ..
200    28
201    25
202    23
203    27
204    25
Name: highway-mpg, Length: 205, dtype: int64

In [45]:
df["highway-mpg"]= 235/df["highway-mpg"]
df.rename(columns={'highway-mpg': 'h-L/100Km'}, inplace=True)

In [48]:
df["h-L/100Km"]

0      27.0
1      27.0
2      26.0
3      30.0
4      22.0
       ...
200    28.0
201    25.0
202    23.0
203    27.0
204    25.0
Name: h-L/100Km, Length: 205, dtype: float64

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,c-L/100km,h-L/100Km,Price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27.0,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27.0,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26.0,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30.0,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22.0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,10.217391,28.0,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,12.368421,25.0,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,13.055556,23.0,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,9.038462,27.0,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,12.368421,25.0,22625.0

In [50]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,c-L/100km,h-L/100Km,Price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27.0,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27.0,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26.0,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30.0,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22.0,17450.0

In [51]:
df["length"]

0      168.8
1      168.8
2      171.2
3      176.6
4      176.6
       ...
200    188.8
201    188.8
202    188.8
203    188.8
204    188.8
Name: length, Length: 205, dtype: float64

In [52]:
df["length"]=df["length"]/df["length"].max()

In [53]:
df['length']

0      0.811148
1      0.811148
2      0.822681
3      0.848630
4      0.848630
         ...
200    0.907256
201    0.907256
202    0.907256
203    0.907256
204    0.907256
Name: length, Length: 205, dtype: float64

In [55]:
df["length"].max()

1.0

In [56]:
df["width"]

0      64.1
1      64.1
2      65.5
3      66.2
4      66.4
       ...
200    68.9
201    68.8
202    68.9
203    68.9
204    68.9
Name: width, Length: 205, dtype: float64